name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule: [cron: "35 23 * * *"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  everything:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install -y lld

      - run: |
          rustup install nightly
          rustup default nightly
          rustup component add clippy
          cargo --version
          cargo clippy --version

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: ". -> cache/target"

      - run: cargo fetch --locked

      - run: cargo check

      - name: cargo clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: cargo test

      - run: cargo run hello
